[project]
name = "vidya"
version = "1.0.0"
description = ""
license = "Apache-2.0"
authors = [
    "The Flower Authors <hello@flower.ai>",
]
readme = "README.md"

[flower.components]
serverapp = "vidya.server:app"
clientapp = "vidya.client:app"
